"""run foreign key

Revision ID: 2ba80b8acdf9
Revises: 58c922dd76ed
Create Date: 2018-08-13 20:00:59.935260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ba80b8acdf9'
down_revision = '58c922dd76ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_run_user_id'), 'run', ['user_id'], unique=False)
    op.create_foreign_key(None, 'run', 'user', ['user_id'], ['id'])
    op.drop_column('run', 'ended_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_index(op.f('ix_run_user_id'), table_name='run')
    op.drop_column('run', 'user_id')
    # ### end Alembic commands ###
