"""user and run

Revision ID: 58c922dd76ed
Revises: 
Create Date: 2018-08-10 19:21:40.829542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58c922dd76ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('distance', sa.TEXT(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_id'), 'run', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('password_hash', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_run_id'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
