"""remove time option from run model

Revision ID: e6ffa9a9aa0c
Revises: 2db51ca0949b
Create Date: 2018-08-31 18:41:18.912112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6ffa9a9aa0c'
down_revision = '2db51ca0949b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('run', 'started_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('run', 'date')
    # ### end Alembic commands ###
